# Source: MarineGym (https://github.com/Marine-RL/MarineGym)
# Original: marinegym/controllers/cfg/lee_controller_BlueROVHeavy.yaml
# License: MIT | Paper: Lee et al., arXiv 1003.2005
# Vehicle: BlueROV Heavy (6 thrusters, MarineGym variant)

lee_controller:
  position_gain: [6, 6, 6]
  velocity_gain: [4.7, 4.7, 4.7]
  attitude_gain: [3, 3, 0.15]
  angular_rate_gain: [0.52, 0.52, 0.18]
